theme = "hugo-academic"
baseURL = "https://fnaufel.github.io/"
title = "fnaufel"

publishDir = "../fnaufel.github.io"

languageCode = "pt"
defaultContentLanguage = "pt" 

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
